name: Build and Release Cilium Envoy Proxy Image

on:
  workflow_dispatch:

jobs:
  release:
    name: Release Helm charts
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Enable Docker IPv6
        run: |
          modprobe -v ipv6
          sudo sed -i -e '1s!^{!\{ "ipv6": true, "fixed-cidr-v6": "fd00::/80",!' /etc/docker/daemon.json || echo '{ "ipv6": true, "fixed-cidr-v6": "fd00::/80" }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Login to OCI registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: cilium/proxy
          ref: v1.26
          persist-credentials: false

      - name: Prep for build
        run: |
          git rev-parse HEAD > SOURCE_VERSION
          echo "ENVOY_MINOR_RELEASE=$(cat ENVOY_VERSION | sed 's/envoy-\([0-9]\+\.[0-9]\+\)\..*/v\1/')" >> $GITHUB_ENV
          echo "ENVOY_PATCH_RELEASE=$(cat ENVOY_VERSION | sed 's/^envoy-\([0-9]\+\.[0-9]\+\.[0-9]\+$\)/v\1/')" >> $GITHUB_ENV
          echo "BAZEL_VERSION=$(cat .bazelversion)" >> $GITHUB_ENV
          echo "BUILDER_DOCKER_HASH=$(git ls-tree --full-tree HEAD -- ./Dockerfile.builder.tests | awk '{ print $3 }')" >> $GITHUB_ENV

      - name: Multi-arch build & push master latest
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          provenance: false
          context: "."
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILDER_BASE=quay.io/cilium/cilium-envoy-builder:${{ env.BAZEL_VERSION }}-latest
            ARCHIVE_IMAGE=quay.io/cilium/cilium-envoy-builder:main-archive-latest
            COPY_CACHE_EXT=.new
            BAZEL_BUILD_OPTS="--remote_upload_local_results=false --tcmalloc=gperftools"
          cache-to: type=local,dest=/tmp/buildx-cache,mode=max
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/cilium-envoy:latest
            ghcr.io/${{ github.repository }}/cilium-envoy:${{ github.sha }}
            ghcr.io/${{ github.repository }}/cilium-envoy:${{ env.ENVOY_MINOR_RELEASE }}
            ghcr.io/${{ github.repository }}/cilium-envoy:${{ env.ENVOY_PATCH_RELEASE }}
            ghcr.io/${{ github.repository }}/cilium-envoy:${{ env.ENVOY_MINOR_RELEASE }}-${{ github.sha }}
            ghcr.io/${{ github.repository }}/cilium-envoy:${{ env.ENVOY_PATCH_RELEASE }}-${{ github.sha }}
