name: Build and Release Cilium Envoy Proxy Image

on:
  workflow_dispatch:

jobs:
  release:
    name: Release Helm charts
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Enable Docker IPv6
        run: |
          modprobe -v ipv6
          sudo sed -i -e '1s!^{!\{ "ipv6": true, "fixed-cidr-v6": "fd00::/80",!' /etc/docker/daemon.json || echo '{ "ipv6": true, "fixed-cidr-v6": "fd00::/80" }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Login to OCI registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: cilium/proxy
          ref: main
          persist-credentials: false

      - name: Prep for build
        run: |
          echo "SOURCE_VERSION=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "$SOURCE_VERSION" > SOURCE_VERSION
          echo "ENVOY_MINOR_RELEASE=$(cat ENVOY_VERSION | sed 's/envoy-\([0-9]\+\.[0-9]\+\)\..*/v\1/')" >> $GITHUB_ENV
          echo "ENVOY_PATCH_RELEASE=$(cat ENVOY_VERSION | sed 's/^envoy-\([0-9]\+\.[0-9]\+\.[0-9]\+$\)/v\1/')" >> $GITHUB_ENV
          echo "BAZEL_VERSION=$(cat .bazelversion)" >> $GITHUB_ENV
          echo "BUILDER_DOCKER_HASH=$(git ls-tree --full-tree HEAD -- ./Dockerfile.builder.tests | awk '{ print $3 }')" >> $GITHUB_ENV

      - name: Checking if cilium-envoy-builder image exists
        id: cilium-builder-tag-in-repositories
        shell: bash
        run: |
          if docker buildx imagetools inspect ghcr.io/${{ github.repository }}/cilium-envoy-builder:${{ env.BAZEL_VERSION }}-${{ env.BUILDER_DOCKER_HASH }} &>/dev/null; then
            echo exists="true" >> $GITHUB_OUTPUT
          else
            echo exists="false" >> $GITHUB_OUTPUT
          fi

      - name: PR Multi-arch build & push of Builder image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        if: steps.cilium-builder-tag-in-repositories.outputs.exists == 'false'
        id: docker_build_builder
        with:
          provenance: false
          context: .
          file: ./Dockerfile.builder
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BAZEL_BUILD_OPTS="--define tcmalloc=gperftools"
          tags: |
            ghcr.io/${{ github.repository }}/cilium-envoy-builder:${{ env.BAZEL_VERSION }}-${{ env.BUILDER_DOCKER_HASH }}
            ghcr.io/${{ github.repository }}/cilium-envoy-builder:${{ env.BAZEL_VERSION }}-latest

      - name: Multi-arch build & push of build artifact archive
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          file: ./Dockerfile
          target: builder-archive
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILDER_BASE=ghcr.io/${{ github.repository }}/cilium-envoy-builder:${{ env.BAZEL_VERSION }}-${{ env.BUILDER_DOCKER_HASH }}
            ARCHIVE_IMAGE=ghcr.io/${{ github.repository }}/cilium-envoy-builder:main-archive-latest
            COPY_CACHE_EXT=.new
            BAZEL_BUILD_OPTS="--jobs=HOST_CPUS*.75"
          push: true
          tags: ghcr.io/${{ github.repository }}/cilium-envoy-builder:main-archive-latest

      - name: Cache Docker layers
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: /tmp/buildx-cache
          key: docker-cache-master

      - name: Clear cache
        run: |
          rm -rf /tmp/buildx-cache/*
          docker buildx prune -f

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "."
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILDER_BASE=ghcr.io/${{ github.repository }}/cilium-envoy-builder:${{ env.BAZEL_VERSION }}-${{ env.BUILDER_DOCKER_HASH }}
            ARCHIVE_IMAGE=ghcr.io/${{ github.repository }}/cilium-envoy-builder:main-archive-latest
            COPY_CACHE_EXT=.new
            BAZEL_BUILD_OPTS="--remote_upload_local_results=false --define tcmalloc=gperftools"   |
          cache-to: type=local,dest=/tmp/buildx-cache,mode=max
          tags: |
            ghcr.io/${{ github.repository }}/cilium-envoy:latest
            ghcr.io/${{ github.repository }}/cilium-envoy:${{ github.sha }}
            ghcr.io/${{ github.repository }}/cilium-envoy:${{ env.ENVOY_MINOR_RELEASE }}-${{ github.sha }}
            ghcr.io/${{ github.repository }}/cilium-envoy:${{ env.ENVOY_PATCH_RELEASE }}-${{ github.sha }}
